name: DeathSwap
main: io.github.netdex.DeathSwap.DeathSwap
version: 3.2

commands:
  ds:
    description: The main DeathSwap command.
    usage: "[DeathSwap] Invalid command. Get help by typing /ds"
    permission: DeathSwap.ds
    permission-message: "[DeathSwap] You don't have permission to use this command."
  dsa:
    description: The main admin DeathSwap command.
    usage: "[DeathSwap] Invalid command. Get help by typing /ds"
    permission: DeathSwap.dsa
    permission-message: "[DeathSwap] You don't have permission to use this command."